/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'ecommerce_app_design';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String CARD = 'assets/images/Card.png';
  static const String CASH

  AND COINS = 'assets/images/Cash and coins.png';
  static const String GOOGLE

  PAY

  =

  '

  assets/images/Google Pay.png

  ';

  static const String PAYTM = 'assets/images/Paytm.png';
  static const String AIR1 = 'assets/images/air1.png';
  static const String CREDIT

  CARDS

  =

  '

  assets/images/credit cards.png

  ';

  static const String ECOMMERCE

  COMPLETED ORDER = 'assets/images/ecommerce completed order.png';
  static const String HOME = 'assets/images/home.png';
}
